import type { ExerciseDefinition, JointRule } from "./types";

// Maps every exercise onto a motion archetype (see skeleton.ts) and defines the
// biomechanical rules + coaching content the analyzer consumes. Designed so new
// exercises can be added by appending to this array.

function rule(joint: string, bottomAngle: number, topAngle: number, tolerance: number, label: string): JointRule {
  return { joint, bottomAngle, topAngle, tolerance, label };
}

export const EXERCISES: ExerciseDefinition[] = [
  {
    id: "squat",
    name: "Barbell Squat",
    category: "squat",
    equipment: "Barbell",
    primaryJoint: "kneeAngle",
    repTopAngle: 168,
    repBottomAngle: 95,
    expectedRom: 73,
    group: "lower",
    rules: [
      rule("kneeAngle", 95, 168, 12, "Knee flexion depth"),
      rule("hipAngle", 70, 150, 14, "Hip hinge depth"),
      rule("torso", 12, 40, 12, "Torso lean (keep neutral)"),
      rule("kneeL", 95, 168, 16, "Left/right knee balance"),
    ],
    cues: ["Brace your core", "Keep your chest up", "Drive through your heels"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Bar across the upper traps, feet shoulder-width, toes slightly out.",
      instructions: [
        "Take a breath and brace your core.",
        "Break at the hips and knees, sitting back and down.",
        "Descend until thighs are at least parallel.",
        "Drive through the mid-foot to stand tall.",
      ],
      commonMistakes: ["Knees caving inward", "Rounding the lower back", "Heels lifting off the floor"],
      coachingCues: ["Spread the floor with your feet", "Screw your knees out", "Keep the chest proud"],
    },
  },
  {
    id: "push-up",
    name: "Push-up",
    category: "press",
    equipment: "Bodyweight",
    primaryJoint: "elbowAngle",
    repTopAngle: 160,
    repBottomAngle: 75,
    expectedRom: 85,
    group: "upper",
    rules: [
      rule("elbowAngle", 75, 160, 14, "Elbow extension"),
      rule("torso", 0, 14, 8, "Straight plank line"),
      rule("shoulderAngle", 70, 120, 18, "Scapula control"),
    ],
    cues: ["Squeeze your glutes", "Keep a rigid plank", "Lower with control"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Hands under shoulders, body in a straight line from head to heels.",
      instructions: [
        "Brace the core and glutes to lock a straight line.",
        "Lower the chest toward the floor by bending the elbows.",
        "Keep elbows at roughly a 45° angle to the body.",
        "Press back up until arms are straight.",
      ],
      commonMistakes: ["Sagging hips", "Flared elbows", "Partial range of motion"],
      coachingCues: ["Glue the ribs to the hips", "Lead with the chest", "Breathe out on the push"],
    },
  },
  {
    id: "bench-press",
    name: "Bench Press",
    category: "press",
    equipment: "Barbell",
    primaryJoint: "elbowAngle",
    repTopAngle: 160,
    repBottomAngle: 70,
    expectedRom: 90,
    group: "upper",
    rules: [
      rule("elbowAngle", 70, 160, 14, "Elbow extension"),
      rule("shoulderAngle", 60, 120, 18, "Bar path / scapula"),
      rule("torso", 0, 10, 6, "Arch & lat tension"),
    ],
    cues: ["Plant your feet", "Pull the bar apart", "Retract your scapula"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Lie flat, grip just outside the shoulders, bar over the eyes.",
      instructions: [
        "Set the shoulders by retracting the scapula.",
        "Lower the bar with control to the lower chest.",
        "Keep the wrists stacked over the elbows.",
        "Drive the bar up in a slight diagonal path.",
      ],
      commonMistakes: ["Bouncing the bar", "Widening the elbows too far", "Lifting the hips"],
      coachingCues: ["Tuck the elbows ~45°", "Push the floor away", "Keep tension in the lats"],
    },
  },
  {
    id: "deadlift",
    name: "Deadlift",
    category: "hinge",
    equipment: "Barbell",
    primaryJoint: "hipAngle",
    repTopAngle: 165,
    repBottomAngle: 95,
    expectedRom: 70,
    group: "lower",
    rules: [
      rule("hipAngle", 95, 165, 12, "Hip hinge depth"),
      rule("torso", 18, 45, 10, "Back angle (neutral spine)"),
      rule("kneeAngle", 120, 168, 14, "Knee tracking"),
    ],
    cues: ["Hinge at the hips", "Keep the bar close", "Brace before you pull"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Feet hip-width, bar over mid-foot, grip just outside the legs.",
      instructions: [
        "Brace the core and grip the bar.",
        "Push the hips back and bend the knees until shins touch the bar.",
        "Drive the floor away, extending the hips and knees together.",
        "Lock out standing tall, then reverse with control.",
      ],
      commonMistakes: ["Round back", "Bar drifting away", "Squatting instead of hinging"],
      coachingCues: ["Lats engaged, arms straight", "Grip the floor", "Hips and shoulders rise together"],
    },
  },
  {
    id: "shoulder-press",
    name: "Shoulder Press",
    category: "press",
    equipment: "Dumbbell",
    primaryJoint: "elbowAngle",
    repTopAngle: 160,
    repBottomAngle: 60,
    expectedRom: 100,
    group: "upper",
    rules: [
      rule("elbowAngle", 60, 160, 12, "Elbow lockout"),
      rule("torso", 0, 12, 8, "Avoid excessive back arch"),
      rule("shoulderAngle", 120, 175, 12, "Overhead path"),
    ],
    cues: ["Keep the ribs down", "Drive the head through", "Squeeze at the top"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Dumbbells at shoulder height, palms forward, core braced.",
      instructions: [
        "Press the weights overhead in a vertical line.",
        "Avoid shrugging or arching the lower back.",
        "Lock the elbows at the top.",
        "Lower with control back to the shoulders.",
      ],
      commonMistakes: ["Over-arching the back", "Leaning back", "Uneven press"],
      coachingCues: ["Tuck the chin slightly", "Brace the abs", "Lead with the elbows"],
    },
  },
  {
    id: "pull-up",
    name: "Pull-up",
    category: "press",
    equipment: "Bodyweight",
    primaryJoint: "elbowAngle",
    repTopAngle: 165,
    repBottomAngle: 50,
    expectedRom: 115,
    group: "upper",
    rules: [
      rule("elbowAngle", 50, 165, 12, "Elbow flexion"),
      rule("shoulderAngle", 60, 150, 16, "Scapula depression"),
      rule("torso", 0, 14, 8, "Minimize sway"),
    ],
    cues: ["Engage your lats", "Pull the elbows down", "Control the descent"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Grip the bar slightly wider than shoulders, hang with straight arms.",
      instructions: [
        "Depress the scapula and engage the lats.",
        "Pull the chest toward the bar by driving the elbows down.",
        "Chin clears the bar at the top.",
        "Lower under control to a full hang.",
      ],
      commonMistakes: ["Kipping", "Partial reps", "Shrugging"],
      coachingCues: ["Think elbows to the floor", "Slow negative", "Hollow body position"],
    },
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "press",
    equipment: "Cable",
    primaryJoint: "elbowAngle",
    repTopAngle: 160,
    repBottomAngle: 55,
    expectedRom: 105,
    group: "upper",
    rules: [
      rule("elbowAngle", 55, 160, 12, "Elbow flexion"),
      rule("torso", 0, 18, 8, "Lean control"),
      rule("shoulderAngle", 70, 150, 16, "Scapula depression"),
    ],
    cues: ["Pull the bar to the chest", "Engage the lats", "Control the eccentric"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Grip wider than shoulders, slight lean, chest up.",
      instructions: [
        "Pull the bar down to the upper chest.",
        "Drive the elbows down and back.",
        "Squeeze the lats at the bottom.",
        "Return slowly to a full stretch.",
      ],
      commonMistakes: ["Using momentum", "Leaning too far back", "Shrugging"],
      coachingCues: ["Lead with the chest", "Engage the lats", "Slow negative"],
    },
  },
  {
    id: "row",
    name: "Bent-over Row",
    category: "pull",
    equipment: "Barbell",
    primaryJoint: "elbowAngle",
    repTopAngle: 150,
    repBottomAngle: 60,
    expectedRom: 90,
    group: "upper",
    rules: [
      rule("elbowAngle", 60, 150, 12, "Elbow flexion"),
      rule("torso", 20, 50, 10, "Hinge angle (neutral spine)"),
      rule("shoulderAngle", 60, 130, 16, "Scapula retraction"),
    ],
    cues: ["Hinge the hips", "Pull to the lower ribs", "Squeeze the shoulder blades"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Hinge at the hips, flat back, arms hanging to the floor.",
      instructions: [
        "Brace the core and keep a neutral spine.",
        "Pull the bar toward the lower ribs.",
        "Squeeze the shoulder blades together.",
        "Lower with control to full extension.",
      ],
      commonMistakes: ["Rounding the back", "Using momentum", "Shrugging"],
      coachingCues: ["Hips stay high", "Elbows behind the body", "Squeeze at the top"],
    },
  },
  {
    id: "lunge",
    name: "Walking Lunge",
    category: "lunge",
    equipment: "Bodyweight",
    primaryJoint: "kneeAngle",
    repTopAngle: 168,
    repBottomAngle: 95,
    expectedRom: 73,
    group: "lower",
    rules: [
      rule("kneeAngle", 95, 168, 12, "Front knee depth"),
      rule("torso", 0, 14, 8, "Upright torso"),
      rule("kneeL", 95, 168, 16, "Left/right balance"),
    ],
    cues: ["Stay tall", "Front knee over ankle", "Drive through the front heel"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Stand tall, take a long step forward.",
      instructions: [
        "Step forward and lower until the back knee nears the floor.",
        "Keep the front knee tracking over the toe.",
        "Drive through the front heel to stand.",
        "Alternate legs as you walk.",
      ],
      commonMistakes: ["Front knee collapsing inward", "Leaning forward", "Short steps"],
      coachingCues: ["Chest proud", "Core braced", "Land softly"],
    },
  },
  {
    id: "plank",
    name: "Plank Hold",
    category: "isometric",
    equipment: "Bodyweight",
    primaryJoint: "spine",
    repTopAngle: 175,
    repBottomAngle: 150,
    expectedRom: 25,
    group: "core",
    rules: [
      rule("torso", 0, 8, 6, "Straight line"),
      rule("spine", 150, 178, 8, "No hip sag / no pike"),
      rule("shoulderAngle", 70, 120, 18, "Scapula set"),
    ],
    cues: ["Glue the ribs to the hips", "Squeeze the glutes", "Breathe steadily"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Forearms on the floor, elbows under shoulders, body straight.",
      instructions: [
        "Brace the core and glutes.",
        "Keep a straight line from head to heels.",
        "Breathe slowly and avoid holding the breath.",
        "Hold with control, no sagging or piking.",
      ],
      commonMistakes: ["Hips sagging", "Butt too high", "Holding the breath"],
      coachingCues: ["Picture a glass of water on your back", "Drive the heels back", "Engage the quads"],
    },
  },
  {
    id: "biceps-curl",
    name: "Biceps Curl",
    category: "pull",
    equipment: "Dumbbell",
    primaryJoint: "elbowAngle",
    repTopAngle: 160,
    repBottomAngle: 45,
    expectedRom: 115,
    group: "upper",
    rules: [
      rule("elbowAngle", 45, 160, 10, "Elbow flexion"),
      rule("torso", 0, 12, 8, "No body swing"),
      rule("shoulderAngle", 70, 110, 16, "Elbow pinned to side"),
    ],
    cues: ["Pin the elbows", "Squeeze at the top", "Lower with control"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Stand tall, dumbbells at the sides, palms forward.",
      instructions: [
        "Keep the elbows pinned to the torso.",
        "Curl the weights up by flexing the elbows.",
        "Squeeze the biceps at the top.",
        "Lower slowly to full extension.",
      ],
      commonMistakes: ["Swinging the body", "Flared elbows", "Rushing the eccentric"],
      coachingCues: ["Elbows to the ribs", "Slow negative", "Full stretch at the bottom"],
    },
  },
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    category: "press",
    equipment: "Cable",
    primaryJoint: "elbowAngle",
    repTopAngle: 70,
    repBottomAngle: 160,
    expectedRom: 90,
    group: "upper",
    rules: [
      rule("elbowAngle", 160, 70, 12, "Elbow extension"),
      rule("torso", 0, 12, 8, "Upright stance"),
      rule("shoulderAngle", 70, 120, 18, "Elbow pinned"),
    ],
    cues: ["Pin the elbows", "Push down and slightly back", "Squeeze the triceps"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Rope or bar at chest height, elbows pinned to the sides.",
      instructions: [
        "Brace the core and keep the elbows at the ribs.",
        "Extend the elbows, pushing the cable down.",
        "Squeeze the triceps at the bottom.",
        "Return slowly to the start.",
      ],
      commonMistakes: ["Flared elbows", "Leaning into the stack", "Partial lockout"],
      coachingCues: ["Elbows to the ribs", "Push slightly back", "Full lockout"],
    },
  },
  {
    id: "leg-press",
    name: "Leg Press",
    category: "squat",
    equipment: "Machine",
    primaryJoint: "kneeAngle",
    repTopAngle: 165,
    repBottomAngle: 95,
    expectedRom: 70,
    group: "lower",
    rules: [
      rule("kneeAngle", 95, 165, 12, "Knee flexion depth"),
      rule("hipAngle", 70, 150, 14, "Hip path"),
      rule("torso", 0, 10, 6, "Lower back on pad"),
    ],
    cues: ["Keep the lower back pinned", "Drive through the heels", "Control the descent"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Seated, feet mid-platform shoulder-width, knees tracking over toes.",
      instructions: [
        "Brace and keep the lower back on the pad.",
        "Lower the platform with control.",
        "Do not let the lower back lift off.",
        "Drive through the heels to extend.",
      ],
      commonMistakes: ["Lower back lifting", "Knees caving in", "Shallow range"],
      coachingCues: ["Heels grounded", "Knees out", "Controlled negative"],
    },
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "hinge",
    equipment: "Barbell",
    primaryJoint: "hipAngle",
    repTopAngle: 165,
    repBottomAngle: 100,
    expectedRom: 65,
    group: "lower",
    rules: [
      rule("hipAngle", 100, 165, 12, "Hip hinge depth"),
      rule("torso", 20, 50, 10, "Back angle (neutral spine)"),
      rule("kneeAngle", 130, 168, 12, "Soft knee"),
    ],
    cues: ["Push the hips back", "Bar close to the legs", "Feel the hamstrings stretch"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Stand tall, soft knees, bar in front of the thighs.",
      instructions: [
        "Hinge at the hips, pushing them back.",
        "Slide the bar down the thighs with soft knees.",
        "Stop when you feel a hamstring stretch.",
        "Drive the hips forward to stand.",
      ],
      commonMistakes: ["Round back", "Bending the knees too much", "Bar drifting away"],
      coachingCues: ["Hips go back", "Chin neutral", "Slow on the way down"],
    },
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    category: "hinge",
    equipment: "Barbell",
    primaryJoint: "hipAngle",
    repTopAngle: 170,
    repBottomAngle: 90,
    expectedRom: 80,
    group: "lower",
    rules: [
      rule("hipAngle", 90, 170, 12, "Hip extension"),
      rule("torso", 0, 12, 8, "Stable trunk"),
      rule("kneeAngle", 90, 130, 14, "Knee angle at top"),
    ],
    cues: ["Drive through the heels", "Squeeze the glutes", "Full lockout at the top"],
    tutorial: {
      demoVideoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      setup: "Upper back on a bench, bar over the hips, shins vertical.",
      instructions: [
        "Plant the feet and brace the core.",
        "Drive the hips up by squeezing the glutes.",
        "Reach full hip extension at the top.",
        "Lower with control.",
      ],
      commonMistakes: ["Over-arching the back", "Knees caving in", "Shallow lockout"],
      coachingCues: ["Ribs down", "Knees out", "Chin tucked"],
    },
  },
];

export const EXERCISE_MAP: Record<string, ExerciseDefinition> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e])
);

export function getExercise(id: string): ExerciseDefinition {
  return EXERCISE_MAP[id] ?? EXERCISES[0];
}

export const EXERCISE_GROUPS = [
  { id: "all", label: "All" },
  { id: "lower", label: "Lower Body" },
  { id: "upper", label: "Upper Body" },
  { id: "core", label: "Core" },
] as const;
