import { IndianFoodItem } from "@/types/fitness-state";

export const INDIAN_FOODS_DATABASE: IndianFoodItem[] = [
  // SOUTH INDIAN BREAKFAST & STAPLES
  {
    id: "in_idli_sambar",
    name: "Idli with Sambar & Chutney",
    regionalName: "ఇడ్లీ సాంబార్ / இட்லி சாம்பார்",
    category: "Breakfast",
    region: "South",
    dietType: "vegan",
    servingSize: "3 idlis + 1 cup sambar + 2 tbsp coconut chutney",
    calories: 320,
    proteinGrams: 9,
    carbsGrams: 58,
    fatGrams: 6,
    fiberGrams: 5,
    estimatedCostINR: 35,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Steam-fermented easy digestion. Drink extra sambar to boost dal-based lentil protein.",
  },
  {
    id: "in_plain_dosa",
    name: "Plain / Masala Dosa",
    regionalName: "దోశ / தோசை",
    category: "Breakfast",
    region: "South",
    dietType: "veg",
    servingSize: "1 medium dosa with potato masala + sambar",
    calories: 380,
    proteinGrams: 7,
    carbsGrams: 54,
    fatGrams: 14,
    fiberGrams: 4,
    estimatedCostINR: 45,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Pair with a double bowl of sambar or add an egg on top (Egg Dosa) for a superior protein ratio.",
  },
  {
    id: "in_medu_vada",
    name: "Medu Vada (2 pcs)",
    regionalName: "గారెలు / மெது வடை",
    category: "Breakfast",
    region: "South",
    dietType: "vegan",
    servingSize: "2 pieces with chutney",
    calories: 360,
    proteinGrams: 8,
    carbsGrams: 30,
    fatGrams: 22,
    fiberGrams: 3,
    estimatedCostINR: 30,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "High in fats due to deep frying. Limit to 1 piece and pair with idli for balanced energy.",
  },
  {
    id: "in_upma",
    name: "Rava / Semolina Upma",
    regionalName: "ఉప్మా / உப்புமா",
    category: "Breakfast",
    region: "South",
    dietType: "vegan",
    servingSize: "1 medium bowl (200g)",
    calories: 250,
    proteinGrams: 6,
    carbsGrams: 44,
    fatGrams: 6,
    fiberGrams: 3,
    estimatedCostINR: 20,
    proteinQuality: "low",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Top with roasted peanuts or have with a cup of curd to improve amino acid completeness.",
  },
  {
    id: "in_poha",
    name: "Flattened Rice Poha with Peanuts",
    regionalName: "పోహా / पोहा",
    category: "Breakfast",
    region: "Pan-India",
    dietType: "vegan",
    servingSize: "1 plate (200g)",
    calories: 270,
    proteinGrams: 7,
    carbsGrams: 46,
    fatGrams: 7,
    fiberGrams: 4,
    estimatedCostINR: 25,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Great iron-rich breakfast carbs. Squeeze fresh lemon to optimize non-heme iron absorption.",
  },
  {
    id: "in_pongal",
    name: "Ven Pongal (Rice & Moong Dal)",
    regionalName: "పొంగల్ / பொங்கல்",
    category: "Breakfast",
    region: "South",
    dietType: "veg",
    servingSize: "1 plate with sambar",
    calories: 340,
    proteinGrams: 10,
    carbsGrams: 52,
    fatGrams: 10,
    fiberGrams: 4,
    estimatedCostINR: 35,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Moong dal + rice provides complete complementary protein. Black pepper aids thermogenesis.",
  },

  // HIGH PROTEIN INDIAN FOODS & HACKS (BUDGET FAVORITES)
  {
    id: "in_soya_chunks_curry",
    name: "Soya Chunks Curry",
    regionalName: "సోయా కర్రీ / सोया चंक्स",
    category: "Protein Source",
    region: "Pan-India",
    dietType: "vegan",
    servingSize: "50g dry soya cooked (1 big bowl)",
    calories: 220,
    proteinGrams: 26,
    carbsGrams: 16,
    fatGrams: 3,
    fiberGrams: 6,
    estimatedCostINR: 15,
    proteinQuality: "high",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "🏆 #1 Budget Protein Hack! Over 52% raw protein per 100g dry weight at under ₹15 per serving.",
  },
  {
    id: "in_boiled_eggs",
    name: "Boiled Eggs (3 Whole)",
    regionalName: "ఉడకబెట్టిన గుడ్లు / उबले अंडे",
    category: "Protein Source",
    region: "Pan-India",
    dietType: "eggitarian",
    servingSize: "3 large boiled eggs",
    calories: 210,
    proteinGrams: 18,
    carbsGrams: 1.5,
    fatGrams: 14,
    fiberGrams: 0,
    estimatedCostINR: 21,
    proteinQuality: "high",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "100% biological value protein. Perfect for hostel rooms without cooking equipment.",
  },
  {
    id: "in_egg_bhurji",
    name: "Egg Bhurji / Scramble (2 Eggs)",
    regionalName: "ఎగ్ బుర్జీ / अंडा भुर्जी",
    category: "Breakfast",
    region: "Pan-India",
    dietType: "eggitarian",
    servingSize: "2 eggs cooked with onions, tomatoes & green chillies",
    calories: 190,
    proteinGrams: 13,
    carbsGrams: 4,
    fatGrams: 13,
    fiberGrams: 1,
    estimatedCostINR: 25,
    proteinQuality: "high",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Pair with 2 whole wheat rotis for a complete 22g protein, 350-calorie post-workout meal.",
  },
  {
    id: "in_egg_curry",
    name: "Dhaba Egg Curry (2 Eggs)",
    regionalName: "గుడ్డు పులుసు / अंडा करी",
    category: "Dinner",
    region: "Pan-India",
    dietType: "eggitarian",
    servingSize: "2 eggs in onion-tomato gravy",
    calories: 260,
    proteinGrams: 14,
    carbsGrams: 8,
    fatGrams: 18,
    fiberGrams: 2,
    estimatedCostINR: 35,
    proteinQuality: "high",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Hostel mess jackpot: prioritize the whole eggs and combine with 2 rotis over white rice.",
  },
  {
    id: "in_paneer_raw",
    name: "Fresh Low-Fat Paneer / Cottage Cheese",
    regionalName: "పన్నీర్ / पनीर",
    category: "Protein Source",
    region: "North",
    dietType: "veg",
    servingSize: "100g raw / lightly tossed",
    calories: 265,
    proteinGrams: 18,
    carbsGrams: 3,
    fatGrams: 20,
    fiberGrams: 0,
    estimatedCostINR: 45,
    proteinQuality: "high",
    isHostelStaple: false,
    isBudgetFriendly: false,
    ojasTip: "Rich in slow-digesting casein protein. Excellent pre-sleep recovery snack to prevent muscle breakdown.",
  },
  {
    id: "in_paneer_bhurji",
    name: "Paneer Bhurji with Roti",
    regionalName: "పన్నీర్ బుర్జీ / पनीर भुर्जी",
    category: "Lunch",
    region: "North",
    dietType: "veg",
    servingSize: "150g paneer bhurji + 2 rotis",
    calories: 520,
    proteinGrams: 24,
    carbsGrams: 42,
    fatGrams: 26,
    fiberGrams: 6,
    estimatedCostINR: 75,
    proteinQuality: "high",
    isHostelStaple: false,
    isBudgetFriendly: false,
    ojasTip: "Wholesome vegetarian muscle-building dinner. Ask for less oil if eating in mess or restaurant.",
  },
  {
    id: "in_sattu_drink",
    name: "Sattu Chana Drink (High Protein)",
    regionalName: "సత్తు డ్రింక్ / सत्तू का शरबत",
    category: "Protein Source",
    region: "East",
    dietType: "vegan",
    servingSize: "40g roasted gram flour (sattu) in water with roasted jeera",
    calories: 165,
    proteinGrams: 11,
    carbsGrams: 26,
    fatGrams: 2.5,
    fiberGrams: 7,
    estimatedCostINR: 15,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Known as the 'Desi Protein Shake'. Zero cooking needed, highly hydrating with natural electrolytes.",
  },
  {
    id: "in_curd_dahi",
    name: "Plain Curd / Dahi (1 Bowl)",
    regionalName: "పెరుగు / दही",
    category: "Snack",
    region: "Pan-India",
    dietType: "veg",
    servingSize: "150g fresh curd",
    calories: 110,
    proteinGrams: 6,
    carbsGrams: 8,
    fatGrams: 6,
    fiberGrams: 0,
    estimatedCostINR: 15,
    proteinQuality: "high",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Natural probiotics for gut microbiome health. Mix with half a scoop whey or roasted flaxseeds.",
  },
  {
    id: "in_roasted_peanuts",
    name: "Roasted Peanuts / Chana",
    regionalName: "వేరుశెనగ గుళ్ళు / भुनी मूंगफली",
    category: "Snack",
    region: "Pan-India",
    dietType: "vegan",
    servingSize: "40g handful",
    calories: 230,
    proteinGrams: 10,
    carbsGrams: 9,
    fatGrams: 19,
    fiberGrams: 3.5,
    estimatedCostINR: 12,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Calorie-dense budget power snack. Great during study sessions or bulking phases.",
  },
  {
    id: "in_sprouts_salad",
    name: "Moong Sprouts Salad with Lemon",
    regionalName: "మొలకలు / मूंग स्प्राउट्स",
    category: "Snack",
    region: "Pan-India",
    dietType: "vegan",
    servingSize: "1 big bowl (150g)",
    calories: 140,
    proteinGrams: 11,
    carbsGrams: 24,
    fatGrams: 1,
    fiberGrams: 7,
    estimatedCostINR: 15,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "High fiber and bioactive enzymes. Helps lower blood glucose spikes when eaten before heavy meals.",
  },

  // COMMON INDIAN LUNCH & DINNER MEALS
  {
    id: "in_dal_tadka_rice",
    name: "Dal Tadka with Steamed Rice",
    regionalName: "పప్పు అన్నం / दाल चावल",
    category: "Lunch",
    region: "Pan-India",
    dietType: "vegan",
    servingSize: "1 cup rice + 1 big bowl toor/moong dal",
    calories: 420,
    proteinGrams: 14,
    carbsGrams: 76,
    fatGrams: 6,
    fiberGrams: 7,
    estimatedCostINR: 35,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Classic staple. To optimize protein density, aim for 1.5:1 dal-to-rice ratio rather than mostly rice.",
  },
  {
    id: "in_rajma_chawal",
    name: "Rajma Masala with Basmati Rice",
    regionalName: "రాజ్మా చావల్ / राजमा चावल",
    category: "Lunch",
    region: "North",
    dietType: "vegan",
    servingSize: "1 plate (1 cup rice + 1.5 cup kidney beans curry)",
    calories: 460,
    proteinGrams: 16,
    carbsGrams: 82,
    fatGrams: 7,
    fiberGrams: 12,
    estimatedCostINR: 50,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "High in soluble fiber and resistant starch, providing sustained 4-hour slow energy release.",
  },
  {
    id: "in_chole_bhature",
    name: "Chole Bhature (2 Bhature)",
    regionalName: "చోలే భటూరే / छोले भटूरे",
    category: "Lunch",
    region: "North",
    dietType: "veg",
    servingSize: "2 fried bhature + 1 bowl chole",
    calories: 780,
    proteinGrams: 17,
    carbsGrams: 96,
    fatGrams: 36,
    fiberGrams: 9,
    estimatedCostINR: 80,
    proteinQuality: "medium",
    isHostelStaple: false,
    isBudgetFriendly: false,
    ojasTip: "Calorie bomb due to refined flour and deep frying. If eaten on cheat day, drink extra water and walk 15 mins.",
  },
  {
    id: "in_roti_dal_sabzi",
    name: "Phulka Roti + Dal + Mixed Sabzi",
    regionalName: "రొట్టెలు పప్పు కూర / रोटी दाल सब्ज़ी",
    category: "Dinner",
    region: "Pan-India",
    dietType: "vegan",
    servingSize: "3 whole wheat phulkas + 1 cup dal + 1 cup bhindi/gobi",
    calories: 450,
    proteinGrams: 16,
    carbsGrams: 74,
    fatGrams: 9,
    fiberGrams: 11,
    estimatedCostINR: 40,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Ideal evening recovery dinner. High complex carbs to aid serotonin and melatonin for deep sleep.",
  },
  {
    id: "in_curd_rice",
    name: "South Indian Curd Rice with Tadka",
    regionalName: "పెరుగన్నం / தயிர் சாதம்",
    category: "Lunch",
    region: "South",
    dietType: "veg",
    servingSize: "1 plate (250g)",
    calories: 310,
    proteinGrams: 8,
    carbsGrams: 48,
    fatGrams: 9,
    fiberGrams: 2,
    estimatedCostINR: 30,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Cools the body and soothes gastrointestinal stress in hot climates. Add pomegranate for antioxidants.",
  },
  {
    id: "in_chicken_breast_curry",
    name: "Home-style Chicken Curry with Roti",
    regionalName: "కోడికూర రొట్టెలు / चिकन करी रोटी",
    category: "Dinner",
    region: "Pan-India",
    dietType: "non-veg",
    servingSize: "150g chicken pieces in gravy + 2 rotis",
    calories: 480,
    proteinGrams: 38,
    carbsGrams: 36,
    fatGrams: 18,
    fiberGrams: 5,
    estimatedCostINR: 90,
    proteinQuality: "high",
    isHostelStaple: false,
    isBudgetFriendly: true,
    ojasTip: "Gold standard 38g complete protein dinner. Supports high muscle protein synthesis.",
  },
  {
    id: "in_chicken_biryani",
    name: "Hyderabadi Chicken Biryani",
    regionalName: "హైదరాబాదీ చికెన్ బిర్యానీ / चिकन बिरयानी",
    category: "Lunch",
    region: "South",
    dietType: "non-veg",
    servingSize: "1 single plate with 2 chicken pieces + raita",
    calories: 680,
    proteinGrams: 32,
    carbsGrams: 78,
    fatGrams: 26,
    fiberGrams: 4,
    estimatedCostINR: 140,
    proteinQuality: "high",
    isHostelStaple: true,
    isBudgetFriendly: false,
    ojasTip: "Good protein from chicken; manage portion size of oil-seasoned basmati rice. Eat with cucumber raita.",
  },
  {
    id: "in_fish_curry_rice",
    name: "Fish Curry with Steamed Rice",
    regionalName: "చేపల పులుసు అన్నం / मछली करी चावल",
    category: "Lunch",
    region: "East",
    dietType: "non-veg",
    servingSize: "150g fish fillet in spicy tamarind/mustard curry + rice",
    calories: 460,
    proteinGrams: 30,
    carbsGrams: 56,
    fatGrams: 12,
    fiberGrams: 3,
    estimatedCostINR: 100,
    proteinQuality: "high",
    isHostelStaple: false,
    isBudgetFriendly: true,
    ojasTip: "Rich in EPA/DHA Omega-3 fatty acids for reducing delayed onset muscle soreness (DOMS) and joint inflammation.",
  },
  {
    id: "in_aloo_paratha",
    name: "Aloo Paratha with Curd & Butter",
    regionalName: "ఆలూ పరోటా / आलू पराठा",
    category: "Breakfast",
    region: "North",
    dietType: "veg",
    servingSize: "1 stuffed paratha + 1 cup curd",
    calories: 390,
    proteinGrams: 9,
    carbsGrams: 52,
    fatGrams: 16,
    fiberGrams: 5,
    estimatedCostINR: 35,
    proteinQuality: "medium",
    isHostelStaple: true,
    isBudgetFriendly: true,
    ojasTip: "Heavy carb loader. Ideal on leg workout days 2 hours prior to lifting heavy sets.",
  },
  {
    id: "in_paneer_paratha",
    name: "Paneer Stuffed Paratha",
    regionalName: "పన్నీర్ పరోటా / पनीर पराठा",
    category: "Breakfast",
    region: "North",
    dietType: "veg",
    servingSize: "1 stuffed paratha with curd",
    calories: 440,
    proteinGrams: 18,
    carbsGrams: 46,
    fatGrams: 20,
    fiberGrams: 4,
    estimatedCostINR: 55,
    proteinQuality: "high",
    isHostelStaple: false,
    isBudgetFriendly: true,
    ojasTip: "Superior breakfast alternative to aloo paratha: 2x the protein and prolonged satiety.",
  }
];

export function searchIndianFoods(query: string, maxResults = 10): IndianFoodItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return INDIAN_FOODS_DATABASE.slice(0, maxResults);

  return INDIAN_FOODS_DATABASE.filter(
    (item) =>
      item.name.toLowerCase().includes(q) ||
      (item.regionalName && item.regionalName.toLowerCase().includes(q)) ||
      item.category.toLowerCase().includes(q) ||
      item.region.toLowerCase().includes(q) ||
      item.dietType.toLowerCase().includes(q)
  ).slice(0, maxResults);
}

export function getBudgetProteinFoods(budgetTier: "low" | "medium" | "high" = "low"): IndianFoodItem[] {
  if (budgetTier === "low") {
    // Top protein per rupee
    return INDIAN_FOODS_DATABASE.filter((f) => f.isBudgetFriendly && f.proteinGrams >= 10);
  }
  return INDIAN_FOODS_DATABASE.filter((f) => f.proteinGrams >= 15);
}

export function getHostelStapleFoods(): IndianFoodItem[] {
  return INDIAN_FOODS_DATABASE.filter((f) => f.isHostelStaple);
}
