export interface ExerciseDefinition {
  id: string; name: string; muscleGroup: string; secondaryMuscles: string[];
  equipment: string; difficulty: string; instructions: string[]; mistakes: string[];
  breathing: string; safety: string; notes: string; beginnerAlternative: string;
  advancedVariation: string; visualUrl: string;
}

export const EXERCISES_DATABASE: ExerciseDefinition[] = [
  { id: "ex_squat", name: "Barbell Back Squat", muscleGroup: "Quads", secondaryMuscles: ["Glutes", "Hamstrings", "Lower Back"], equipment: "Barbell", difficulty: "Advanced", instructions: ["Brace your core and descend under control.", "Drive through your feet to stand."], mistakes: ["Knees caving inward", "Rounding lower back"], breathing: "Inhale on descent; exhale as you stand.", safety: "Use safety pins or a qualified spotter when appropriate.", notes: "Maintain a comfortable, controlled range of motion.", beginnerAlternative: "Dumbbell Goblet Squat", advancedVariation: "Barbell Front Squat", visualUrl: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500&q=80" },
  { id: "ex_bench", name: "Barbell Bench Press", muscleGroup: "Chest", secondaryMuscles: ["Triceps", "Anterior Deltoids"], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Set shoulders and lower the bar with control.", "Press smoothly back to start."], mistakes: ["Bouncing the bar", "Lifting hips"], breathing: "Inhale down; exhale on press.", safety: "Use a spotter when lifting near your limit.", notes: "Keep a stable base through the feet.", beginnerAlternative: "Push-ups", advancedVariation: "Dumbbell Incline Bench Press", visualUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&q=80" },
  { id: "ex_rdl", name: "Romanian Deadlift", muscleGroup: "Hamstrings", secondaryMuscles: ["Glutes", "Erectors", "Grip"], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Hinge at the hips while keeping the load close.", "Stand by driving the hips forward."], mistakes: ["Rounding the back", "Bending knees too much"], breathing: "Inhale during hinge; exhale at lockout.", safety: "Choose a manageable load and keep control.", notes: "Prioritize the hip hinge pattern.", beginnerAlternative: "Kettlebell Hinge", advancedVariation: "Single-leg Dumbbell RDL", visualUrl: "https://images.unsplash.com/photo-1605296867304-46d5465a25f1?w=500&q=80" },
  { id: "ex_pullup", name: "Bodyweight Pull-Up", muscleGroup: "Lats", secondaryMuscles: ["Biceps", "Rhomboids", "Core"], equipment: "Pull-up Bar", difficulty: "Advanced", instructions: ["Engage shoulders before pulling.", "Lower under control."], mistakes: ["Using momentum", "Incomplete range"], breathing: "Exhale as you pull; inhale down.", safety: "Confirm the bar is stable before use.", notes: "Use assistance when needed.", beginnerAlternative: "Lat Pulldown", advancedVariation: "Weighted Pull-Up", visualUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500&q=80" },
  { id: "ex_press", name: "Dumbbell Overhead Press", muscleGroup: "Shoulders", secondaryMuscles: ["Triceps", "Upper Chest"], equipment: "Dumbbells", difficulty: "Intermediate", instructions: ["Keep the core braced.", "Press vertically with control."], mistakes: ["Overarching lower back", "Incomplete range"], breathing: "Exhale while pressing.", safety: "Use a load you can control without discomfort.", notes: "Avoid leaning back.", beginnerAlternative: "Seated Dumbbell Press", advancedVariation: "Standing Barbell Press", visualUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500&q=80" },
];
