import { SportProfile, SportAttributeDefinition, SportAttributeKey } from "./types";

export const SPORT_ATTRIBUTES: Record<SportAttributeKey, SportAttributeDefinition> = {
  acceleration: {
    id: "acceleration",
    name: "Acceleration & Linear Speed",
    unit: "pts (10m/20m split)",
    description: "Ability to reach peak speed from a static or low-speed start.",
    testName: "20-Meter Sprint Acceleration Test",
    testProtocol: "Timed electronic sprint over 20 meters from stationary athletic stance.",
  },
  agility: {
    id: "agility",
    name: "Agility & Change of Direction",
    unit: "pts (COD seconds)",
    description: "Ability to rapidly decelerate, reorient, and explode in a new direction.",
    testName: "5-10-5 Pro Agility / Illinois Test",
    testProtocol: "Rapid lateral shuttles with cone touches measuring change of direction cadence.",
  },
  endurance: {
    id: "endurance",
    name: "Cardiorespiratory & Aerobic Capacity",
    unit: "pts (VO2/Beep level)",
    description: "Ability to sustain moderate-to-high intensity output across a full match or session.",
    testName: "Yo-Yo Intermittent Recovery / 1.5 Mile Run",
    testProtocol: "Shuttle run intervals with active recovery measuring aerobic recovery rate.",
  },
  lower_body_power: {
    id: "lower_body_power",
    name: "Lower-Body Explosive Power",
    unit: "pts (CMJ cm / Watts)",
    description: "Vertical and horizontal triple-extension power output (hips, knees, ankles).",
    testName: "Vertical Jump (CMJ) / Standing Broad Jump",
    testProtocol: "Maximal vertical countermovement jump measured on contact mat or video lens.",
  },
  upper_body_strength: {
    id: "upper_body_strength",
    name: "Upper-Body Strength & Hypertrophy",
    unit: "pts (1RM/Rep Max)",
    description: "Pushing, pulling, and pressing force production against resistance.",
    testName: "Push-Up Max / Pull-Up Max / Bench Press Ratio",
    testProtocol: "Standardized strict push-ups to cadence or bodyweight relative load test.",
  },
  core_stability: {
    id: "core_stability",
    name: "Core Stability & Anti-Rotation",
    unit: "pts (Plank/Hold sec)",
    description: "Transfer of force between upper and lower extremities without spinal buckling.",
    testName: "Side Plank & Paloff Anti-Rotation Hold",
    testProtocol: "Timed isometric endurance of anterior, posterior, and lateral kinetic chain.",
  },
  mobility: {
    id: "mobility",
    name: "Joint Mobility & Dynamic Flexibility",
    unit: "pts (Degrees / ROM)",
    description: "Usable active range of motion in ankles, hips, thoracic spine, and shoulders.",
    testName: "Overhead Squat & Shoulder Dislocate ROM",
    testProtocol: "Full kinetic chain screening via Ojas Vision Lens pose tracking.",
  },
  reaction_time: {
    id: "reaction_time",
    name: "Reaction Time & Hand-Eye Coordination",
    unit: "ms (Visual-Motor index)",
    description: "Latency between visual/auditory stimulus and physical motor response.",
    testName: "Visual Light / Dropped Ruler Reaction Test",
    testProtocol: "Response latency measurement to visual cues.",
  },
  rotational_power: {
    id: "rotational_power",
    name: "Rotational Kinetic Power",
    unit: "pts (Med Ball Velocity)",
    description: "Power transfer through the hips and torso for batting, bowling, and throwing.",
    testName: "Seated / Standing Med Ball Rotational Throw",
    testProtocol: "Distance/velocity of 3kg medicine ball lateral throw.",
  },
  repeated_effort: {
    id: "repeated_effort",
    name: "Repeated High-Intensity Effort (RHIE)",
    unit: "pts (Fatigue Index %)",
    description: "Ability to recover and repeat maximal sprints or tackles with minimal drop-off.",
    testName: "Repeated Sprint Ability (RSA 6x30m)",
    testProtocol: "Six consecutive 30m sprints on 25-second turnarounds.",
  },
};

export const SPORT_REGISTRY: Record<string, SportProfile> = {
  cricket: {
    id: "cricket",
    name: "Cricket",
    category: "field",
    icon: "🏏",
    tagline: "Rotational Power, Sprint Acceleration & Bowling Shoulder Resilience",
    overview: "Cricket demands intermittent explosive sprint efforts, high rotational trunk velocity for bowling and batting, shoulder resilience, and rapid hand-eye reaction.",
    primaryEnergySystem: "Mixed Hybrid",
    keyInjuryRisks: ["Lumbar spine stress fractures (fast bowlers)", "Rotator cuff tendinitis", "Hamstring sprint strains"],
    requiredAttributes: [
      { attributeId: "rotational_power", foundationTarget: 55, developmentTarget: 70, performanceTarget: 84, advancedTarget: 92, weightInSport: 5, rationale: "Vital for batting exit velocity and bowling power transfer." },
      { attributeId: "acceleration", foundationTarget: 50, developmentTarget: 68, performanceTarget: 82, advancedTarget: 90, weightInSport: 5, rationale: "Essential for 22-yard running between wickets and boundary fielding." },
      { attributeId: "mobility", foundationTarget: 60, developmentTarget: 72, performanceTarget: 85, advancedTarget: 92, weightInSport: 4, rationale: "Thoracic spine and glenohumeral rotation safeguard against stress injuries." },
      { attributeId: "reaction_time", foundationTarget: 55, developmentTarget: 70, performanceTarget: 85, advancedTarget: 94, weightInSport: 4, rationale: "Critical for slip catching, wicketkeeping, and fast ball tracking." },
      { attributeId: "core_stability", foundationTarget: 52, developmentTarget: 68, performanceTarget: 80, advancedTarget: 88, weightInSport: 4, rationale: "Stabilizes trunk against asymmetric bowling loads." },
      { attributeId: "endurance", foundationTarget: 50, developmentTarget: 65, performanceTarget: 78, advancedTarget: 86, weightInSport: 3, rationale: "Supports full 50-over or multi-day fielding stamina in humid heat." },
    ],
    recommendedTests: [
      { attributeId: "rotational_power", testName: "Rotational Med Ball Throw", description: "Measure throw distance from left and right batting stance." },
      { attributeId: "acceleration", testName: "22-Yard Run a Three Sprint", description: "Timed shuttle mimicking 3 runs between wickets with bat." },
      { attributeId: "mobility", testName: "Thoracic Rotation Test", description: "Active rotation angle in seated lumbar lock." },
    ],
    signatureDrills: [
      { name: "Single-Arm Rotational Cable Press", targetAttribute: "rotational_power", durationMinutes: 12, description: "Explosive drive from back hip through torso into straight punch.", coachingCue: "Pivot back foot like a cover drive.", equipment: "Cable or Resistance Band" },
      { name: "Wicket Shuttle Sprints (3x22 yards)", targetAttribute: "acceleration", durationMinutes: 10, description: "Low acceleration sprint, decelerate to line touch, explode back.", coachingCue: "Drop hips low at turn, drive arms forward.", equipment: "Cones" },
      { name: "Prone Y-T-W Shoulder Complex", targetAttribute: "mobility", durationMinutes: 8, description: "Scapular retractor and rotator cuff strengthening on floor.", coachingCue: "Pinch shoulder blades without shrugging traps.", equipment: "Bodyweight" },
    ],
    recoveryConsiderations: {
      criticalMuscleGroups: ["Posterior Deltoids & Rotator Cuff", "Quadratus Lumborum (Lower Back)", "Hamstrings"],
      hydrationFocus: "Electrolyte replacement critical during 4+ hour sun exposure matches.",
      restDayRecommendation: "Active recovery walk + gentle thoracic foam rolling post bowling days.",
    },
  },

  football: {
    id: "football",
    name: "Football / Soccer",
    category: "field",
    icon: "⚽",
    tagline: "Agility, Repeated Sprint Conditioning & Lower-Body Power",
    overview: "Football requires covering 8-12 km per match with 40-60 intermittent maximal sprints, rapid 360-degree cuts, and physical contested duels.",
    primaryEnergySystem: "Mixed Hybrid",
    keyInjuryRisks: ["ACL and Meniscus tears from cutting", "Hamstring eccentric sprint strain", "Groin / Adductor tendinopathy"],
    requiredAttributes: [
      { attributeId: "agility", foundationTarget: 58, developmentTarget: 74, performanceTarget: 88, advancedTarget: 95, weightInSport: 5, rationale: "Rapid lateral cuts, pressing, and evasion in tight spaces." },
      { attributeId: "endurance", foundationTarget: 60, developmentTarget: 76, performanceTarget: 89, advancedTarget: 96, weightInSport: 5, rationale: "Sustaining match-long 90-minute work rate without tactical fatigue." },
      { attributeId: "repeated_effort", foundationTarget: 55, developmentTarget: 72, performanceTarget: 86, advancedTarget: 93, weightInSport: 5, rationale: "Sprint recovery repeatability across attacking and defensive transitions." },
      { attributeId: "lower_body_power", foundationTarget: 52, developmentTarget: 70, performanceTarget: 84, advancedTarget: 91, weightInSport: 4, rationale: "Shooting velocity, aerial headers, and tackle absorption." },
      { attributeId: "acceleration", foundationTarget: 56, developmentTarget: 72, performanceTarget: 86, advancedTarget: 94, weightInSport: 4, rationale: "First 5-10m burst to win 50/50 loose balls." },
      { attributeId: "mobility", foundationTarget: 50, developmentTarget: 66, performanceTarget: 78, advancedTarget: 86, weightInSport: 3, rationale: "Adductor and hip flexor range of motion protects against groin pulls." },
    ],
    recommendedTests: [
      { attributeId: "agility", testName: "Illinois Agility Run", description: "Course with weaving cones and turning sprints." },
      { attributeId: "endurance", testName: "Yo-Yo Intermittent Recovery Level 1", description: "20m shuttle beep test with 10s active recoveries." },
      { attributeId: "lower_body_power", testName: "Standing Broad Jump", description: "Horizontal two-foot explosion distance." },
    ],
    signatureDrills: [
      { name: "5-10-5 Pro Agility Shuttles", targetAttribute: "agility", durationMinutes: 12, description: "Explosive 5m right, 10m left, 5m sprint through center.", coachingCue: "Stay in low athletic center of gravity on cuts.", equipment: "Cones" },
      { name: "Nordic Hamstring Curls", targetAttribute: "lower_body_power", durationMinutes: 10, description: "Eccentric kneeling lower with partner or anchor hold.", coachingCue: "Resist downward drop with hamstrings as long as possible.", equipment: "Anchor or Partner" },
      { name: "Aerobic Power Shuttles (15s on / 15s off)", targetAttribute: "repeated_effort", durationMinutes: 15, description: "High-intensity box-to-box strides on 1:1 work-to-rest ratio.", coachingCue: "Maintain stride length through final repetitions.", equipment: "Pitch / Ground" },
    ],
    recoveryConsiderations: {
      criticalMuscleGroups: ["Hamstrings (Biceps Femoris)", "Groin & Adductors", "Calves & Achilles"],
      hydrationFocus: "High carbohydrate + sodium replenishing within 30 mins post match.",
      restDayRecommendation: "Hydrotherapy or gentle bike spin to flush lower-body metabolic waste.",
    },
  },

  badminton: {
    id: "badminton",
    name: "Badminton",
    category: "racket",
    icon: "🏸",
    tagline: "Explosive Lunging, Rapid Reaction & Rotational Mobility",
    overview: "Fastest racket sport in the world requiring lightning reaction speeds, explosive multi-directional lunges, overhead jump smashes, and intense short-burst conditioning.",
    primaryEnergySystem: "Anaerobic Lactic",
    keyInjuryRisks: ["Achilles tendinopathy", "Patellar tendinitis (Jumper's knee)", "Rotator cuff shoulder impingement"],
    requiredAttributes: [
      { attributeId: "agility", foundationTarget: 60, developmentTarget: 76, performanceTarget: 90, advancedTarget: 96, weightInSport: 5, rationale: "Rapid 6-corner court recovery and directional shifts." },
      { attributeId: "reaction_time", foundationTarget: 62, developmentTarget: 78, performanceTarget: 92, advancedTarget: 97, weightInSport: 5, rationale: "Responding to 300+ km/h smash returns in fractions of a second." },
      { attributeId: "lower_body_power", foundationTarget: 55, developmentTarget: 72, performanceTarget: 86, advancedTarget: 93, weightInSport: 4, rationale: "Explosive scissors jumps and deep lunging recovery power." },
      { attributeId: "mobility", foundationTarget: 58, developmentTarget: 74, performanceTarget: 86, advancedTarget: 93, weightInSport: 4, rationale: "Deep hip abduction in split steps and overhead shoulder extension." },
      { attributeId: "repeated_effort", foundationTarget: 52, developmentTarget: 70, performanceTarget: 84, advancedTarget: 92, weightInSport: 4, rationale: "Maintaining shot sharpness across 60+ minute grueling 3-set rallies." },
      { attributeId: "core_stability", foundationTarget: 50, developmentTarget: 66, performanceTarget: 78, advancedTarget: 86, weightInSport: 3, rationale: "Mid-air body control during jump smashes." },
    ],
    recommendedTests: [
      { attributeId: "agility", testName: "Badminton 6-Corner Shadow Footwork Test", description: "Timed shadow court transitions to 6 boundary points." },
      { attributeId: "reaction_time", testName: "Visual Shuttle Drop Reaction Test", description: "Drop catch latency testing peripheral reaction." },
      { attributeId: "lower_body_power", testName: "Single-Leg Forward Lunge Recovery Test", description: "Time to lunge deep and push back to central base." },
    ],
    signatureDrills: [
      { name: "Shadow Footwork Interval Pyramids", targetAttribute: "agility", durationMinutes: 15, description: "Front net lunges to rear court jump smash simulations at match cadence.", coachingCue: "Keep chest tall, push aggressively from lead heel.", equipment: "Court / Open Space" },
      { name: "Rotational Plyo Split Jumps", targetAttribute: "lower_body_power", durationMinutes: 10, description: "Explosive scissor jump switch with 45-degree hip turn.", coachingCue: "Minimize ground contact time on landing.", equipment: "Bodyweight" },
      { name: "Crossover Lateral Reaction Taps", targetAttribute: "reaction_time", durationMinutes: 8, description: "Rapid side steps touching visual cue markers on whistle/audio.", coachingCue: "Stay on balls of feet, eyes locked forward.", equipment: "Cones" },
    ],
    recoveryConsiderations: {
      criticalMuscleGroups: ["Patellar Tendon & Quads", "Achilles Tendon & Soleus", "Dominant Shoulder Rotator Cuff"],
      hydrationFocus: "Fast electrolyte replenishment due to high indoor humidity & sweat rates.",
      restDayRecommendation: "Calf eccentric stretching + contrast bath immersion for feet.",
    },
  },

  kabaddi: {
    id: "kabaddi",
    name: "Kabaddi",
    category: "combat_contact",
    icon: "🤼",
    tagline: "Explosive Leg Drive, Upper-Body Grip Strength & Breath-Holding Power",
    overview: "Indigenous high-intensity sport requiring explosive raiding acceleration, lower-body tackle evasion, wrestling-level grip and torso strength, and anaerobic breath control.",
    primaryEnergySystem: "Anaerobic Alactic",
    keyInjuryRisks: ["Ankle syndesmosis sprains", "Knee hyperextension during tackles", "Shoulder joint dislocations"],
    requiredAttributes: [
      { attributeId: "lower_body_power", foundationTarget: 62, developmentTarget: 78, performanceTarget: 90, advancedTarget: 96, weightInSport: 5, rationale: "Toe touch lunges, dubki ducks, and explosive tackle escapes." },
      { attributeId: "upper_body_strength", foundationTarget: 60, developmentTarget: 76, performanceTarget: 88, advancedTarget: 95, weightInSport: 5, rationale: "Ankle holds, thigh catches, and chain tackle gripping strength." },
      { attributeId: "agility", foundationTarget: 58, developmentTarget: 74, performanceTarget: 88, advancedTarget: 94, weightInSport: 5, rationale: "Quick raiding footwork to evade 7 defensive defenders." },
      { attributeId: "core_stability", foundationTarget: 60, developmentTarget: 75, performanceTarget: 87, advancedTarget: 94, weightInSport: 5, rationale: "Withstanding multi-player tackle impact forces." },
      { attributeId: "repeated_effort", foundationTarget: 55, developmentTarget: 72, performanceTarget: 85, advancedTarget: 92, weightInSport: 4, rationale: "Repeated 30-second cantilever raids with minimal rest." },
      { attributeId: "reaction_time", foundationTarget: 54, developmentTarget: 70, performanceTarget: 84, advancedTarget: 91, weightInSport: 4, rationale: "Instantaneous corner-chain tackle timing." },
    ],
    recommendedTests: [
      { attributeId: "lower_body_power", testName: "Standing Long Jump & Deep Squat 1RM", description: "Explosive horizontal extension force." },
      { attributeId: "upper_body_strength", testName: "Towel Pull-Up / Isometric Grip Dynamometer", description: "Grip endurance and pulling power." },
      { attributeId: "agility", testName: "Zig-Zag Raiding Shuttle Drill", description: "Low-stance weaving through 5 lateral defenders." },
    ],
    signatureDrills: [
      { name: "Heavy Sandbag / Kettlebell Clean & Front Squat", targetAttribute: "lower_body_power", durationMinutes: 14, description: "Explosive hip extension from floor into solid deep catch.", coachingCue: "Drive hips through violently, lock core at top.", equipment: "Sandbag / Weight" },
      { name: "Dubki Low Evasion Shuttles", targetAttribute: "agility", durationMinutes: 10, description: "Rapid sprint drop under mock horizontal chain arm and explode upward.", coachingCue: "Drop hips without rounding spine.", equipment: "Rope / Obstacle" },
      { name: "Isometric Farmer's Walk Grip Finisher", targetAttribute: "upper_body_strength", durationMinutes: 8, description: "Heavy bilateral load carry with tall upright posture.", coachingCue: "Squeeze handles like you are locking an ankle hold.", equipment: "Dumbbells / Buckets" },
    ],
    recoveryConsiderations: {
      criticalMuscleGroups: ["Glutes & Adductors", "Forearms & Latissimus Dorsi", "Trapezius & Neck"],
      hydrationFocus: "Heavy electrolyte and high protein recovery for muscle tissue repair.",
      restDayRecommendation: "Warm mustard oil self-massage (Abhyanga) + gentle hip joint mobility.",
    },
  },

  basketball: {
    id: "basketball",
    name: "Basketball",
    category: "court",
    icon: "🏀",
    tagline: "Vertical Jump Power, Lateral Deceleration & Court Speed",
    overview: "Fast-paced dynamic court sport demanding vertical rim explosion, rapid lateral defensive slides, transition speed, and high-frequency anaerobic endurance.",
    primaryEnergySystem: "Mixed Hybrid",
    keyInjuryRisks: ["Lateral ankle ligament sprains", "Patellar tendinitis", "Finger jam/sprains"],
    requiredAttributes: [
      { attributeId: "lower_body_power", foundationTarget: 60, developmentTarget: 76, performanceTarget: 89, advancedTarget: 96, weightInSport: 5, rationale: "Rebounding, shot blocking, and layups require peak vertical jump." },
      { attributeId: "agility", foundationTarget: 58, developmentTarget: 74, performanceTarget: 88, advancedTarget: 95, weightInSport: 5, rationale: "Defensive perimeter slides and crossover changes of direction." },
      { attributeId: "acceleration", foundationTarget: 55, developmentTarget: 72, performanceTarget: 85, advancedTarget: 93, weightInSport: 4, rationale: "Fast-break transitions from defensive paint to offensive rim." },
      { attributeId: "repeated_effort", foundationTarget: 54, developmentTarget: 70, performanceTarget: 84, advancedTarget: 92, weightInSport: 4, rationale: "Maintains shooting form and defensive intensity in 4th quarter." },
      { attributeId: "core_stability", foundationTarget: 50, developmentTarget: 68, performanceTarget: 80, advancedTarget: 88, weightInSport: 3, rationale: "Mid-air contact balance when finishing contested layups." },
      { attributeId: "mobility", foundationTarget: 52, developmentTarget: 66, performanceTarget: 78, advancedTarget: 86, weightInSport: 3, rationale: "Ankle dorsiflexion absorbs high-impact repetitive jump landings." },
    ],
    recommendedTests: [
      { attributeId: "lower_body_power", testName: "Standing Vertical Jump & Approach Jump", description: "Measure max reach difference." },
      { attributeId: "agility", testName: "Lane Agility Drill", description: "Standard NBA combine court perimeter shuttle." },
      { attributeId: "repeated_effort", testName: "17-Sprint Court Baseline Shuttles", description: "Timed cross-court baseline touches." },
    ],
    signatureDrills: [
      { name: "Depth Jump to Maximal Vertical Explosion", targetAttribute: "lower_body_power", durationMinutes: 12, description: "Step off 30cm box, land soft, immediately explode into max vertical jump.", coachingCue: "Spring off the floor immediately upon touch.", equipment: "Plyo Box" },
      { name: "Defensive Slide + Closeout Drills", targetAttribute: "agility", durationMinutes: 10, description: "3 lateral slides right, drop step, sprint to closeout cone with high hand.", coachingCue: "Keep feet wide, never cross ankles during slides.", equipment: "Cones" },
    ],
    recoveryConsiderations: {
      criticalMuscleGroups: ["Patellar Tendon & Calves", "Lower Back", "Quadriceps"],
      hydrationFocus: "Intra-game electrolyte sipping to prevent cramp onset.",
      restDayRecommendation: "Foam roll IT band and quads; ankle mobility band flossing.",
    },
  },

  athletics: {
    id: "athletics",
    name: "Athletics / Running",
    category: "track_running",
    icon: "🏃",
    tagline: "Stride Mechanics, Aerobic Base & Core Power Transfer",
    overview: "Pure track and field performance spanning middle-distance endurance, sprint mechanics, running economy, and symmetrical kinetic chain power.",
    primaryEnergySystem: "Aerobic",
    keyInjuryRisks: ["Medial Tibial Stress Syndrome (Shin splints)", "Plantar Fasciitis", "IT Band Friction Syndrome"],
    requiredAttributes: [
      { attributeId: "endurance", foundationTarget: 65, developmentTarget: 80, performanceTarget: 92, advancedTarget: 98, weightInSport: 5, rationale: "Foundational VO2 max and lactate threshold engine." },
      { attributeId: "repeated_effort", foundationTarget: 60, developmentTarget: 76, performanceTarget: 88, advancedTarget: 95, weightInSport: 5, rationale: "Pacing consistency across interval and tempo sessions." },
      { attributeId: "core_stability", foundationTarget: 55, developmentTarget: 70, performanceTarget: 84, advancedTarget: 92, weightInSport: 4, rationale: "Prevents pelvic drop and trunk sway during late-race fatigue." },
      { attributeId: "lower_body_power", foundationTarget: 52, developmentTarget: 68, performanceTarget: 82, advancedTarget: 90, weightInSport: 4, rationale: "Ground contact impulse and stride turnover speed." },
      { attributeId: "mobility", foundationTarget: 54, developmentTarget: 68, performanceTarget: 80, advancedTarget: 88, weightInSport: 3, rationale: "Hip extension range allows longer natural stride without overstriding." },
      { attributeId: "acceleration", foundationTarget: 50, developmentTarget: 65, performanceTarget: 78, advancedTarget: 86, weightInSport: 3, rationale: "Early race positioning and final sprint finish kick." },
    ],
    recommendedTests: [
      { attributeId: "endurance", testName: "Cooper 12-Minute Run Test", description: "Total distance covered in 12 minutes on 400m track." },
      { attributeId: "repeated_effort", testName: "1000m Interval Repeat Test", description: "Consistency across 4x1000m on 2min rest." },
      { attributeId: "core_stability", testName: "Single-Leg Glute Bridge Hold", description: "Pelvic level stability endurance per side." },
    ],
    signatureDrills: [
      { name: "A-Skips & B-Skips Stride Mechanics", targetAttribute: "lower_body_power", durationMinutes: 10, description: "High knee drive with active foot claw under center of mass.", coachingCue: "Strike ground underneath hips with stiff ankle.", equipment: "Track / Flat ground" },
      { name: "Tempo Interval Strides (5x400m)", targetAttribute: "endurance", durationMinutes: 18, description: "Controlled 85% pace efforts targeting lactate threshold.", coachingCue: "Relax shoulders and maintain steady rhythmic breathing.", equipment: "Track / Stopwatch" },
    ],
    recoveryConsiderations: {
      criticalMuscleGroups: ["Tibialis Anterior & Calves", "Plantar Fascia", "Hip Flexors (Psoas)"],
      hydrationFocus: "Steady hydration with sodium before long morning runs.",
      restDayRecommendation: "Deep tissue calf massage + non-weight-bearing swimming or cycling.",
    },
  },

  volleyball: {
    id: "volleyball",
    name: "Volleyball",
    category: "court",
    icon: "🏐",
    tagline: "Spike Elevation, Overhead Power & Lateral Block Speed",
    overview: "High-flying court sport characterized by repeated vertical jump spikes, defensive dive digs, quick lateral net blocking, and dominant shoulder power.",
    primaryEnergySystem: "Anaerobic Alactic",
    keyInjuryRisks: ["Shoulder impingement (Spiker's shoulder)", "Jumper's knee", "Ankle sprains from under-net landings"],
    requiredAttributes: [
      { attributeId: "lower_body_power", foundationTarget: 60, developmentTarget: 76, performanceTarget: 90, advancedTarget: 97, weightInSport: 5, rationale: "Spike approach jump height and block elevation." },
      { attributeId: "reaction_time", foundationTarget: 58, developmentTarget: 74, performanceTarget: 88, advancedTarget: 95, weightInSport: 5, rationale: "Reading ball trajectory and opponent spike direction." },
      { attributeId: "agility", foundationTarget: 56, developmentTarget: 72, performanceTarget: 86, advancedTarget: 93, weightInSport: 4, rationale: "Lateral net blocking shuffle and defensive floor coverage." },
      { attributeId: "rotational_power", foundationTarget: 54, developmentTarget: 70, performanceTarget: 84, advancedTarget: 92, weightInSport: 4, rationale: "Arm swing acceleration and core torque when spiking." },
      { attributeId: "mobility", foundationTarget: 52, developmentTarget: 68, performanceTarget: 80, advancedTarget: 88, weightInSport: 3, rationale: "Thoracic spine extension prevents lumbar hyper-arch during spikes." },
      { attributeId: "repeated_effort", foundationTarget: 50, developmentTarget: 66, performanceTarget: 78, advancedTarget: 86, weightInSport: 3, rationale: "Repeats 80-120 maximal jumps across a 5-set match." },
    ],
    recommendedTests: [
      { attributeId: "lower_body_power", testName: "Spike Approach Jump Test", description: "3-step approach vertical touch height." },
      { attributeId: "reaction_time", testName: "Ball Deflection Reaction Drill", description: "Reaction latency to deflected ball trajectory." },
    ],
    signatureDrills: [
      { name: "3-Step Spike Approach Plyometrics", targetAttribute: "lower_body_power", durationMinutes: 12, description: "Left-right-left penultimate step plant into max vertical block jump.", coachingCue: "Swing both arms back aggressively, convert horizontal speed into vertical lift.", equipment: "Court" },
      { name: "Band External Rotation & Scapular Pull-Apart", targetAttribute: "rotational_power", durationMinutes: 8, description: "Shoulder stability primer for spiking arm.", coachingCue: "Keep elbow pinned to rib cage during rotation.", equipment: "Mini Band" },
    ],
    recoveryConsiderations: {
      criticalMuscleGroups: ["Infraspinatus / Supraspinatus", "Patellar Tendons", "Thoracic Spine"],
      hydrationFocus: "Standard sports electrolyte replenishment.",
      restDayRecommendation: "Sleeper stretch for shoulder internal rotation + quad foam rolling.",
    },
  },

  hockey: {
    id: "hockey",
    name: "Field Hockey",
    category: "field",
    icon: "🏑",
    tagline: "Low-Posture Trunk Endurance, Stick Handling Speed & Multi-Sprint Stamina",
    overview: "High-intensity turf sport demanding prolonged crouched trunk flexion, rapid stick dribbling acceleration, explosive drag flicking, and relentless 60-minute running.",
    primaryEnergySystem: "Mixed Hybrid",
    keyInjuryRisks: ["Lumbar erector fatigue & strain", "Hamstring sprint strain", "Hand and shin impact contusions"],
    requiredAttributes: [
      { attributeId: "endurance", foundationTarget: 60, developmentTarget: 76, performanceTarget: 89, advancedTarget: 96, weightInSport: 5, rationale: "Non-stop turf running on water-based synthetic pitches." },
      { attributeId: "core_stability", foundationTarget: 62, developmentTarget: 78, performanceTarget: 90, advancedTarget: 96, weightInSport: 5, rationale: "Sustaining low athletic crouch stance without spinal fatigue." },
      { attributeId: "agility", foundationTarget: 58, developmentTarget: 74, performanceTarget: 87, advancedTarget: 94, weightInSport: 5, rationale: "Rapid 1v1 stick elimination moves and counter-pressing." },
      { attributeId: "rotational_power", foundationTarget: 54, developmentTarget: 70, performanceTarget: 84, advancedTarget: 92, weightInSport: 4, rationale: "Power production for drag flicks, slap hits, and reverse-stick shots." },
      { attributeId: "repeated_effort", foundationTarget: 55, developmentTarget: 72, performanceTarget: 86, advancedTarget: 93, weightInSport: 4, rationale: "Quarter-based rolling substitution sprint intensity." },
      { attributeId: "lower_body_power", foundationTarget: 52, developmentTarget: 68, performanceTarget: 82, advancedTarget: 90, weightInSport: 3, rationale: "First-step burst out of penalty corner defense." },
    ],
    recommendedTests: [
      { attributeId: "core_stability", testName: "Isometric Low-Crouch Hold Test", description: "Timed hold in match hockey posture." },
      { attributeId: "agility", testName: "T-Drill Turf Shuttle", description: "Forward, lateral slide, and backward backpedal sprint." },
    ],
    signatureDrills: [
      { name: "Low-Stance Lateral Resisted Band Walks", targetAttribute: "core_stability", durationMinutes: 10, description: "Glute medius and lumbar isometric hold in 45-degree crouch.", coachingCue: "Keep stick height level, hips low, spine neutral.", equipment: "Loop Band" },
      { name: "Explosive Drag Flick Med Ball Slams", targetAttribute: "rotational_power", durationMinutes: 12, description: "Lateral lunging stride into rotational power throw.", coachingCue: "Transfer weight from back foot to front foot dynamically.", equipment: "Med Ball" },
    ],
    recoveryConsiderations: {
      criticalMuscleGroups: ["Erector Spinae & Quadratus Lumborum", "Hamstrings", "Gluteus Medius"],
      hydrationFocus: "Critical hydration due to heat reflection from synthetic turf.",
      restDayRecommendation: "Cat-cow spinal mobility + hamstring active stretches.",
    },
  },
};
